# Parameters for apriltag detector node
family: "tag36h11"
ndetectors: 1
nthreads: 1
quad_decimate: 10.0
quad_sigma: 0.0
refine_edges: 0
decode_sharpening: 0.25
tag_size: 0.09
detection_freq: 1.0
rectify_alpha: 0.0